services:
    #
    # Search engine
    #
    ExtendedSearchQueryBundle\Service\SearchEngine:
        class: ExtendedSearchQueryBundle\Service\SearchEngine
        calls:
            - [setDispatcher, ["@event_dispatcher"]]
